typography_spectrum: 0.685727221891284
color:
  brandStrength: 0.6717986799776554
  lightness: 0.4442029215861112
  saturation: 0.08573235920630395
  rhythmicContrast: 0.7237238420639187
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
layout_spectrum: 0.8555122741963714
author:
  email: info@eurocaution-benelux.com
  name: Alessandro Rizzo
name: EuroCaution Benelux SA
navigation:
  - name: ImmoCaution
    url: www.immocaution.eu
    type: external
  - name: Qui sommes-nous ?
    id: 0ebb00fc-b80d-48ca-81fa-360e0d4b7ba1
    type: content
title: EuroCaution Benelux SA
description: Courtier-souscripteur en assurances
