typography_spectrum: 0.790672647068277
color:
  brandStrength: 0.8438615298364311
  lightness: 0.9558383992407471
  saturation: 0.7714370246976614
  rhythmicContrast: 0.025774152716621757
  brandColors:
    - '#E1E6FA'
    - '#C4D7ED'
    - '#ABC8E2'
    - '#375D81'
    - '#183152'
layout_spectrum: 0.5809122135397047
author:
  email: info@eurocaution-benelux.com
  name: Alessandro Rizzo
name: EuroCaution Benelux SA
navigation:
  - name: ImmoCaution
    url: www.immocaution.eu
    type: external
title: EuroCaution Benelux SA
description: Courtier-souscripteur en assurances
