typography_spectrum: 0.8568433043546975
color:
  brandStrength: 0.9113317027222365
  lightness: 0.5368401110172272
  saturation: 0.38066312531009316
  rhythmicContrast: 0.46571922837756574
  brandColors:
    - '#001D5C'
    - '#6E6965'
    - '#BFC6D6'
    - '#7F8EAD'
    - '#EFF1F6'
layout_spectrum: 0.8206884951796383
author:
  email: info@eurocaution-benelux.com
  name: Alessandro Rizzo
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/06eb071a-2af2-40f6-b248-1ea9eb15385c.gif
name: EuroCaution Benelux SA
navigation:
  - name: ImmoCaution
    url: www.immocaution.eu
    type: external
  - name: Qui sommes-nous ?
    id: 0ebb00fc-b80d-48ca-81fa-360e0d4b7ba1
    type: content
title: EuroCaution Benelux SA
description: Courtier-souscripteur en assurances
