typography_spectrum: 0.32276050630025566
color:
  brandStrength: 0.45557846827432513
  lightness: 0.9510974297299981
  saturation: 0.378653216175735
  rhythmicContrast: 0.26438326644711196
  brandColors:
    - '#16193B'
    - '#35478C'
    - '#4E7AC7'
    - '#7FB2F0'
    - '#ADD5F7'
layout_spectrum: 0.7365620436612517
author:
  email: info@eurocaution-benelux.com
  name: Alessandro Rizzo
name: EuroCaution Benelux SA
navigation: []
title: EuroCaution Benelux SA
description: Courtier-souscripteur en assurances
