typography_spectrum: 0.9070391748100519
color:
  brandStrength: 0.8558436075691134
  lightness: 0.9538798246067017
  saturation: 0.55988566018641
  rhythmicContrast: 0.8174859592691064
  brandColors:
    - '#1A1F2B'
    - '#30395C'
    - '#4A6491'
    - '#85A5CC'
    - '#D0E4F2'
layout_spectrum: 0.4995566764846444
author:
  email: info@eurocaution-benelux.com
  name: Alessandro Rizzo
name: EuroCaution Benelux SA
navigation:
  - name: ImmoCaution
    url: www.immocaution.eu
    type: external
title: EuroCaution Benelux SA
description: Courtier-souscripteur en assurances
